import { Categories } from 'hap-nodejs';

export const categoriesMap: Record<Yandex.DeviceType, Categories> = {
  'devices.types.camera': Categories.CAMERA,
  'devices.types.cooking': Categories.OTHER,
  'devices.types.cooking.coffee_maker': Categories.OTHER,
  'devices.types.cooking.kettle': Categories.OTHER,
  'devices.types.cooking.multicooker': Categories.OTHER,
  'devices.types.dishwasher': Categories.OTHER,
  'devices.types.humidifier': Categories.AIR_HUMIDIFIER,
  'devices.types.iron': Categories.OTHER,
  'devices.types.light': Categories.LIGHTBULB,
  'devices.types.media_device': Categories.TELEVISION,
  'devices.types.media_device.receiver': Categories.TELEVISION,
  'devices.types.media_device.tv': Categories.TELEVISION,
  'devices.types.media_device.tv_box': Categories.TV_SET_TOP_BOX,
  'devices.types.openable': Categories.DOOR,
  'devices.types.openable.curtain': Categories.WINDOW_COVERING,
  'devices.types.other': Categories.OTHER,
  'devices.types.pet_drinking_fountain': Categories.OTHER,
  'devices.types.pet_feeder': Categories.OTHER,
  'devices.types.purifier': Categories.AIR_PURIFIER,
  'devices.types.sensor': Categories.SENSOR,
  'devices.types.sensor.button': Categories.SWITCH,
  'devices.types.sensor.climate': Categories.SENSOR,
  'devices.types.sensor.gas': Categories.SENSOR,
  'devices.types.sensor.illumination': Categories.SENSOR,
  'devices.types.sensor.motion': Categories.SECURITY_SYSTEM,
  'devices.types.sensor.open': Categories.SENSOR,
  'devices.types.sensor.smoke': Categories.SENSOR,
  'devices.types.sensor.vibration': Categories.SENSOR,
  'devices.types.sensor.water_leak': Categories.SENSOR,
  'devices.types.smart_meter': Categories.SENSOR,
  'devices.types.smart_meter.cold_water': Categories.SENSOR,
  'devices.types.smart_meter.electricity': Categories.SENSOR,
  'devices.types.smart_meter.gas': Categories.SENSOR,
  'devices.types.smart_meter.heat': Categories.SENSOR,
  'devices.types.smart_meter.hot_water': Categories.SENSOR,
  'devices.types.socket': Categories.OUTLET,
  'devices.types.switch': Categories.SWITCH,
  'devices.types.thermostat': Categories.THERMOSTAT,
  'devices.types.thermostat.ac': Categories.AIR_CONDITIONER,
  'devices.types.vacuum_cleaner': Categories.OTHER,
  'devices.types.washing_machine': Categories.OTHER,
};
